'Salesforce.com':
  subdomain:
    - 'salesforce.com'
'Microsoft Office 365':
  subdomain:
    - 'sharepoint.com'
  subdirectory:
    - 'outlook.office.com/owa/'
    - 'outlook.office365.com/owa/'
'Box.com':
  subdomain:
    - 'box.com'
    - 'account.box.com'
'Slack':
  subdomain:
    - 'slack.com'
    - 'enterprise.slack.com'
'Zendesk':
  subdomain:
    - 'zendesk.com'
'Oracle Cloud':
  subdomain:
    - 'oraclecloud.com'
  status:
    - 'testing'
'Cisco (Webex)':
  subdomain:
    - 'webex.com'
'ServiceNow':
  subdomain:
    - 'service-now.com'
'GitHub':
  subdirectory:
    - 'github.com/'
'Workday':
  subdomain:
    - 'myworkdayjobs.com'
'Coupa':
  subdomain:
    - 'coupa.com'
    - 'coupahost.com'
# 'Atlassian':
#   subdomain:
#     - 'atlassian.net'
'Shopify':
  subdomain:
    - 'shopifyapps.com'
'Mailchimp':
  subdomain:
    - 'mailchimpsites.com'
    - 'mailchi.mp'
'Zoom':
  subdomain:
    - 'zoom.us'
'Okta':
  subdomain:
    - 'okta.com'
'OneLogin':
  subdomain:
    - 'onelogin.com'
'SabaCloud':
  subdomain:
    - 'sabacloud.com'
'Qualtrics':
  subdomain:
    - 'qualtrics.com'
    - 'az1.qualtrics.com'
'Citrix ShareFile':
  subdomain:
    - 'sharefile.com'
'MapTq.com':
  subdomain:
    - 'maptq.com'
'Activ Absence':
  subdomain:
    - 'activabsence.co.uk'
'Blue Jeans Network':
  subdomain:
    - 'bluejeans.com'
'iPR Software':
  subdomain:
    - 'iprsoftware.com'
'NICE inContact':
  subdomain:
    - 'nice-incontact.com'
'Oath':
  subdomain:
    - 'oath.com'
    - 'mydashboard.oath.com'
'Plateau':
  subdomain:
    - 'plateau.com'
'Uservoice':
  subdomain:
    - 'uservoice.com'
'Remarkety':
  subdomain:
    - 'remarkety.com'
'TurboVote':
  subdomain:
    - 'turbovote.org'
